language: clojure
lein: lein2
script: lein2 do clean, test
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
notifications:
  recipients:
    - ogeagla@gmail.com