version: '2'
services:
  dstream-server:
    image: dstream-server
    environment:
      RPC_PORT: "2104"
  dstream-int-test:
    image: dstream-int-test
    depends_on:
      - dstream-server
    environment:
      RPC_CLIENT_HOST: "dstream-server"
